#!/usr/bin/env python3

import os
import socket
import struct

mac = os.urandom(6)

s = socket.socket(socket.AF_UNIX)
s.connect("/tmp/ble.socket")
s.send(struct.pack("<IB", len(mac)+1, 0x01) + mac)
rsp_length = int.from_bytes(s.recv(4), "little")
rsp = s.recv(rsp_length)
s.close()

print(f"Random mac {mac.hex()} sent ({rsp.hex()})")

